AWSTemplateFormatVersion: 2010-09-09
Description: "NAT managed service deployment"
Parameters:
  SubnetId:
    Description: "The public subnet in which to create the NAT gateway"
    Type: "AWS::EC2::Subnet::Id"
  RouteTable:
    Description: "Private route table ID"
    Type: String
  
Resources:
  NAT:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref SubnetId #required
  
  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
 
  Route:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NAT
      RouteTableId: !Ref RouteTable #required
  
  
  
  